-- 2026-09-18 hentai_archive 三范式化迁移
--
-- 目标：
--   1. hentai_gallery   —— 画廊实体（title / title_hash / gid 只存一处）
--   2. hentai_archive_event —— 归档事件（对某画廊的一次状态处理）
--   3. 同名视图 hentai_archive 顶替旧表，列名与旧表完全一致 → 读取代码零改动
--   4. RPC upsert_hentai_archive 原子完成「画廊 upsert + 事件 upsert」，写路径唯一入口
--
-- 旧表改名为 hentai_archive_legacy 保留，回滚即：drop view hentai_archive; alter table hentai_archive_legacy rename to hentai_archive;
--
-- 全部语句在单个事务内执行，任一断言失败则整体回滚，前端不受影响。

begin;

-- ---------------------------------------------------------------- 1. 画廊实体表
create table public.hentai_gallery (
  id           bigint generated by default as identity primary key,
  user_id      uuid        not null default auth.uid() references auth.users (id) on delete cascade,
  title        varchar(255) not null,
  title_hash   varchar(64)  not null,
  gid          bigint       not null,
  created_time timestamptz  not null default now(),
  updated_time timestamptz  not null default now(),
  constraint hentai_gallery_title_not_empty check (btrim(title) <> ''),
  constraint hentai_gallery_title_hash_format check (title_hash ~ '^[0-9a-f]{64}$'),
  constraint hentai_gallery_user_id_title_hash_unique unique (user_id, title_hash)
);

comment on table public.hentai_gallery is '画廊实体：同一标题 hash 一行，title/title_hash/gid 的唯一存放处';
comment on column public.hentai_gallery.gid is '最近一次见到/处理的 gid（画廊重传会变动，仅作元数据，不参与判重）';
comment on column public.hentai_gallery.updated_time is '最后一次写入时刻';

-- ---------------------------------------------------------------- 2. 归档事件表
create table public.hentai_archive_event (
  id             bigint generated by default as identity primary key,
  user_id        uuid        not null default auth.uid() references auth.users (id) on delete cascade,
  gallery_id     bigint      not null references public.hentai_gallery (id) on delete cascade,
  status         bigint      not null,
  watermark_date timestamptz not null,
  updated_time   timestamptz not null default now(),
  constraint hentai_archive_event_status_domain check (status in (200, 304, 400)),
  constraint hentai_archive_event_user_id_gallery_id_status_unique unique (user_id, gallery_id, status)
);

comment on table public.hentai_archive_event is '归档事件：仅描述"对某画廊在某状态下的一次处理结果"';
comment on column public.hentai_archive_event.status is '200=已提交最新种子 304=只有过时种子 400=用户主动跳过';
comment on column public.hentai_archive_event.watermark_date is '判重水位线：200 写画廊日期，304 写种子 Posted 日期';
comment on column public.hentai_archive_event.user_id is '有意冗余：便于 RLS 保持 auth.uid() = user_id 的简单形式，可由 gallery.user_id 推出';

-- 视图 join 需要按 gallery_id 反查事件
create index hentai_archive_event_gallery_id_idx on public.hentai_archive_event (gallery_id);

-- ---------------------------------------------------------------- 3. RLS
alter table public.hentai_gallery enable row level security;
alter table public.hentai_archive_event enable row level security;

create policy "Enable users to crud their own data only" on public.hentai_gallery
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Enable users to crud their own data only" on public.hentai_archive_event
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------- 4. 权限
grant select, insert, update, delete on public.hentai_gallery to authenticated;
grant select, insert, update, delete on public.hentai_archive_event to authenticated;

-- ---------------------------------------------------------------- 5. 数据搬迁
-- 注意：窗口列必须另起别名（first_time/last_time），否则 ORDER BY created_time 会按输出别名排序，
-- 导致 distinct on 选中的不是"最后一次写入的那一行"，gid 会取错。
insert into public.hentai_gallery (user_id, title, title_hash, gid, created_time, updated_time)
select distinct on (user_id, title_hash)
       user_id,
       title,
       title_hash,
       gid,
       min(created_time) over w as first_time,
       max(created_time) over w as last_time
from public.hentai_archive
window w as (partition by user_id, title_hash)
order by user_id, title_hash, created_time desc;

insert into public.hentai_archive_event (user_id, gallery_id, status, watermark_date, updated_time)
select a.user_id, g.id, a.status, a.date, a.created_time
from public.hentai_archive a
join public.hentai_gallery g on g.user_id = a.user_id and g.title_hash = a.title_hash;

-- ---------------------------------------------------------------- 6. 断言
do $$
declare
  v_src_rows  bigint;
  v_src_hash  bigint;
  v_event     bigint;
  v_gallery   bigint;
begin
  select count(*), count(distinct (user_id, title_hash)) into v_src_rows, v_src_hash from public.hentai_archive;
  select count(*) into v_event from public.hentai_archive_event;
  select count(*) into v_gallery from public.hentai_gallery;

  if v_event <> v_src_rows then
    raise exception '归档事件行数不一致：源 % / 新 %', v_src_rows, v_event;
  end if;
  if v_gallery <> v_src_hash then
    raise exception '画廊行数不一致：源 % / 新 %', v_src_hash, v_gallery;
  end if;
  if exists (
    select 1
    from public.hentai_archive a
    join public.hentai_gallery g on g.user_id = a.user_id and g.title_hash = a.title_hash
    join public.hentai_archive_event e on e.gallery_id = g.id and e.status = a.status
    where e.watermark_date <> a.date or e.updated_time <> a.created_time
  ) then
    raise exception '搬迁后的水位线/时间与原表不一致';
  end if;
  if (select count(*) from public.hentai_archive_event where gallery_id is null) > 0 then
    raise exception '存在未关联画廊的归档事件';
  end if;

  raise notice '搬迁校验通过：% 行事件 / % 行画廊', v_event, v_gallery;
end $$;

-- ---------------------------------------------------------------- 7. 切换：旧表改名，同名视图接管读路径
alter table public.hentai_archive rename to hentai_archive_legacy;

create view public.hentai_archive with (security_invoker = true) as
select a.id,
       g.gid,
       a.watermark_date as date,
       a.user_id,
       a.updated_time   as created_time,
       a.status,
       g.title,
       g.title_hash
from public.hentai_archive_event a
join public.hentai_gallery g on g.id = a.gallery_id;

comment on view public.hentai_archive is '兼容视图：列名与旧表一致，读路径零改动；写入走 upsert_hentai_archive()';

grant select on public.hentai_archive to authenticated;

-- ---------------------------------------------------------------- 8. 写入 RPC
create or replace function public.upsert_hentai_archive(
  p_gid    bigint,
  p_title  text,
  p_date   timestamptz,
  p_status bigint
)
returns table (
  id             bigint,
  user_id        uuid,
  gallery_id     bigint,
  status         bigint,
  watermark_date timestamptz,
  updated_time   timestamptz,
  gid            bigint,
  title          varchar(255),
  title_hash     varchar(64)
)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_hash       varchar(64);
  v_gallery_id bigint;
begin
  if p_title is null or btrim(p_title) = '' then
    raise exception 'title 不能为空';
  end if;

  -- 与前端 sha256Hex(title) 等价的派生逻辑
  v_hash := encode(sha256(convert_to(p_title, 'UTF8')), 'hex');

  -- 注：output 参数名与列名同名（便于前端直接映射），因此 ON CONFLICT 必须用约束名，
  -- 且所有列引用都要用表别名限定，否则 PL/pgSQL 会把标识符解析为变量 → 42702 ambiguous
  insert into public.hentai_gallery as gal (title, title_hash, gid)
  values (p_title, v_hash, p_gid)
  on conflict on constraint hentai_gallery_user_id_title_hash_unique do update
    set title        = excluded.title,
        title_hash   = excluded.title_hash,
        gid          = excluded.gid,
        updated_time = now()
  returning gal.id into v_gallery_id;

  return query
  with up as (
    insert into public.hentai_archive_event as ev (gallery_id, status, watermark_date)
    values (v_gallery_id, p_status, p_date)
    on conflict on constraint hentai_archive_event_user_id_gallery_id_status_unique do update
      set watermark_date = excluded.watermark_date,
          updated_time   = now()
    returning ev.*
  )
  select up.id, up.user_id, up.gallery_id, up.status, up.watermark_date, up.updated_time,
         g.gid, g.title, g.title_hash
  from up
  join public.hentai_gallery g on g.id = up.gallery_id;
end;
$$;

comment on function public.upsert_hentai_archive(bigint, text, timestamptz, bigint)
  is '归档写入唯一入口：原子 upsert 画廊 + 事件，返回与旧 DTO 等价的字段';

grant execute on function public.upsert_hentai_archive(bigint, text, timestamptz, bigint) to authenticated;

-- ---------------------------------------------------------------- 8b. 派生列一致性守卫
-- title_hash 是 title 的派生值（sha256），留在同一张表属"受约束的冗余"：
-- 用触发器保证任何写入路径都不会让二者不一致。
create or replace function public.hentai_gallery_assert_title_hash()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.title_hash is distinct from encode(sha256(convert_to(new.title, 'UTF8')), 'hex') then
    raise exception 'title_hash 与 sha256(title) 不一致：%', left(new.title, 40);
  end if;
  return new;
end;
$$;

drop trigger if exists hentai_gallery_assert_title_hash on public.hentai_gallery;
create trigger hentai_gallery_assert_title_hash
  before insert or update of title, title_hash on public.hentai_gallery
  for each row execute function public.hentai_gallery_assert_title_hash();

-- ---------------------------------------------------------------- 9. 让 PostgREST 重新加载 schema
notify pgrst, 'reload schema';

commit;
