name: Send WeChat Notification on Completion

on:
  workflow_run:
    types: ['completed']
    workflows: ["build-and-deploy"]

jobs:
  send-wechat-notification-on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Sending message
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "${{ github.repository }}构建成功 \n
          ${{ github.event.workflow_run.head_commit.message }} \n"
  send-wechat-notification-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Sending message
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "${{ github.repository }}构建成功 \n
          ${{ github.event.workflow_run.head_commit.message }} \n"